@startuml clothingstorage

package "core"
{
    class Storage
    class Clothing
    Class StorageStatistics
}

package "client"
{
    class StorageClient
}

package "localpersistence"
{
    class ClothingStoragePersistence
    class ClothingStorageModule
    class ClothingDeserializer
    class ClothingSerializer
    class StorageDeserializer
    class StorageSerializer
}

package "restserver"
{
    class ClothingStorageApplication
    class ClothingStorageController
    class ClothingStorageService
}

package "ui"
{
    class NewClothingPageController
    class PricePageController
    class StatisticsPageController
    class StoragePageController
    class StorageAppDirect
    class StorageAppRemote
    interface Access
    class DirectAccess
    class RemoteAccess
}

ClothingStorageService ..> ClothingStoragePersistence
ClothingStorageApplication ..> ClothingStoragePersistence

client ..> localpersistence
client ..> core 

localpersistence ..> core

restserver ..> core
restserver ..> localpersistence

ui ..> core
ui ..> client
ui ..> localpersistence


@enduml