@startuml architecture

component core {
	package clothingStorage.core
}

component localpersistence {
	package clothingStorage.json
}

component fxui {
	package clothingStorage.ui
}

clothingStorage.ui ..> clothingStorage.core
clothingStorage.ui ..> clothingStorage.json

component jackson {
}

clothingStorage.json ..> jackson

component javafx {
	component fxml {
	}
}

fxui ..> javafx
fxui ..> fxml

@enduml