@startuml class-diagram

class storage
{
    -HashMap<Clothing, Integer> storageList
    --
    +void addNewClothing(Clothing, int)
    +void removeClothing()
    +void increaseQuantity(Clothing, int)
    +void decreaseQuantity(Clothing, int)
    +List<String> storageDisplay()
    +List<String> priceDisplay(List<Clothing>)
    -boolean isValidQuantity(int)
    +boolean isClothingInStorage(Clothing)
    +int getQuantity(Clothing)
    +LinkedHashMap<Clothing, Integer> gettAllClothes()
    +List<Clothing> sortOnLowestPrice()
    +List<Clothing> sortOnHighestPrice()
    +List<Clothing> filterOnBrand(String)
    +List<Clothing> filterOnType(String)
    +List<Clothing> filterOnSale()
    +Clothing getClothing(int)
    +String toString()

}

class clothing
{
    -String type
    -String brand
    -Char size
    -Double price
    -Double discount
    -String[] validBrands
    --
    +void setType(String)
    -void isValidType(String)
    +void setBrand(String)
    -boolean isValidType(String)
    +void setSize(char)
    +void setPrice(double, boolean)
    +void setDiscount(double)
    +void removeDiscount()
    -boolean isValidDiscount(double)
    +void setSale(double)
    +String getType()
    +String getBrand()
    +char getSize()
    +double getPrice()
    +boolean isOnSale()
    +double getDiscount()
    +String toString()

}

storage <|-- clothing

@enduml