@startuml architecture

component core {
	package clothingStorage.core
}

component fxui {
	package clothingStorage.ui
}

clothingStorage.ui ..> clothingStorage.core
clothingStorage.ui ..> clothingStorage.localpersistence

component localpersistence {
	package clothingStorage.localpersistence
}

component jackson {
}

clothingStorage.localpersistence ..> jackson

component javafx {
	component fxml {
	}
}

fxui ..> javafx
fxui ..> fxml

@enduml